### ISSUE TITLE
Error 404 URL not found

### ISSUE THREAD

**Issue by clairenied15** [clairenied15/heart_rate_sentinel_server#1]
I run my code hr_server.py and then go to 127.0.0.1:5000 in my web browser but get an error that says the URL is not found. If my code were correct, I should be able to see info on this website, correct? And if I go to 127.0.0.1:5000/api/new_patient I should be able to see the dictionary of patient info? I'm still a little confused on the difference between POST vs. GET and how the code for those differs. I pushed my hr_server.py code to GitHub for you to look at.

**Comment by dward2** [comment]
I did receive your issue.  I provided a detailed response by e-mail.  Please let me know if you don't receive it.

**Comment by dward2** [comment]
Also, I forgot to mention, your code is contained in the venv folder.  It probably should not be in there.  I don't know if it will cause any problems, but best practice would be to not include your code in the venv folder.
